language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy
  - pypy3
install:
  - travis_retry pip install -U pip wheel setuptools
  - python setup.py develop dev
script:
  - py.test -rw
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
