language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy3
before_install:
  - pip freeze | xargs pip uninstall -y
install:
  - travis_retry pip install -U pip wheel setuptools
  - pip install -U -e ".[testing]"
script:
  - py.test -rw
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
